/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.paranavai.armarios.view;

import br.edu.ifpr.paranavai.armarios.dao.ArmarioDao;
import br.edu.ifpr.paranavai.armarios.dao.EstudanteDao;
import br.edu.ifpr.paranavai.armarios.entity.Armario;
import br.edu.ifpr.paranavai.armarios.entity.Estudante;
import br.edu.ifpr.paranavai.armarios.utils.OnlyNumbers;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class EditorHomeBibliotecarioUI extends javax.swing.JFrame {
    
    private List<Estudante> listaEstudante = new ArrayList<>();
    private List<Armario> listaArmario = new ArrayList<>();

    /**
     * Creates new form EditorHomeBibliotecario
     */
    public EditorHomeBibliotecarioUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        buscaEstudantes();
        refreshLists();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        fields = new javax.swing.JPanel();
        inputBuscaEstudante = new javax.swing.JTextField();
        buttonBuscarEstudante = new javax.swing.JButton();
        table = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaEstudante = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        fields1 = new javax.swing.JPanel();
        inputBuscarArmarios = new javax.swing.JTextField();
        buttonBuscarArmarios = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaArmarios = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuNovo = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenuItem();
        menuApagar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jPanel2.setLayout(new java.awt.BorderLayout());

        buttonBuscarEstudante.setText("Buscar");
        buttonBuscarEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarEstudanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fieldsLayout = new javax.swing.GroupLayout(fields);
        fields.setLayout(fieldsLayout);
        fieldsLayout.setHorizontalGroup(
            fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(inputBuscaEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBuscarEstudante)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        fieldsLayout.setVerticalGroup(
            fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBuscaEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarEstudante))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.add(fields, java.awt.BorderLayout.PAGE_START);

        table.setLayout(new java.awt.BorderLayout());

        tabelaEstudante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RA", "Nome", "CPF", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tabelaEstudante);
        if (tabelaEstudante.getColumnModel().getColumnCount() > 0) {
            tabelaEstudante.getColumnModel().getColumn(0).setResizable(false);
        }

        table.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanel2.add(table, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Estudantes", jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        buttonBuscarArmarios.setText("Buscar");
        buttonBuscarArmarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarArmariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fields1Layout = new javax.swing.GroupLayout(fields1);
        fields1.setLayout(fields1Layout);
        fields1Layout.setHorizontalGroup(
            fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fields1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(inputBuscarArmarios, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBuscarArmarios)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        fields1Layout.setVerticalGroup(
            fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fields1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBuscarArmarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarArmarios))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.add(fields1, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        tabelaArmarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "N°", "Ativo", "Observações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaArmarios);
        if (tabelaArmarios.getColumnModel().getColumnCount() > 0) {
            tabelaArmarios.getColumnModel().getColumn(0).setResizable(false);
            tabelaArmarios.getColumnModel().getColumn(1).setResizable(false);
            tabelaArmarios.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Armários", jPanel1);

        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        menu.setText("Menu");

        menuNovo.setText("Novo");
        menuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoActionPerformed(evt);
            }
        });
        menu.add(menuNovo);

        menuEditar.setText("Editar");
        menuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarActionPerformed(evt);
            }
        });
        menu.add(menuEditar);

        menuApagar.setText("Apagar");
        menuApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuApagarActionPerformed(evt);
            }
        });
        menu.add(menuApagar);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBuscarEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarEstudanteActionPerformed
        if (!this.inputBuscarArmarios.getText().isEmpty()) {
            List<Estudante> listaEstudanteFiltrada = this.listaEstudante.stream()
                    .filter(l -> l.getNome().toUpperCase()
                    .contains(this.inputBuscaEstudante.getText().toUpperCase())
                    || l.getCpf()
                            .contains(this.inputBuscaEstudante.getText())
                    || l.getRa()
                            .contains(this.inputBuscaEstudante.getText())
                    || l.getEmail().toUpperCase()
                            .contains(this.inputBuscaEstudante.getText().toUpperCase()))
                    .collect(Collectors.toList());
            
            this.setDataTable(listaEstudanteFiltrada);
        } else {
            this.setDataTable(listaEstudante);
        }
    }//GEN-LAST:event_buttonBuscarEstudanteActionPerformed

    private void buttonBuscarArmariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarArmariosActionPerformed
        if (!this.inputBuscarArmarios.getText().isEmpty()) {
            List<Armario> listaArmarioFiltrada = this.listaArmario.stream()
                    .filter(l -> l.getNumero().equals(Integer.valueOf(this.inputBuscarArmarios.getText()))
                    || l.getAtivo().equals(Boolean.valueOf(this.inputBuscarArmarios.getText())))
                    .collect(Collectors.toList());

            this.setDataTable(listaArmarioFiltrada);
        } else {
            this.setDataTable(listaArmario);
        }
    }//GEN-LAST:event_buttonBuscarArmariosActionPerformed

    private void menuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoActionPerformed
        switch (jTabbedPane2.getSelectedIndex()) {
            case 0:
                NovoEstudanteUI novoEstudanteUI = new NovoEstudanteUI();

                this.iconeFrame(novoEstudanteUI);
                novoEstudanteUI.setTitle("Cadastro Novo Estudante");
                novoEstudanteUI.setVisible(true);
                
                break;
                
            case 1:
                
                break;
        }
    }//GEN-LAST:event_menuNovoActionPerformed

    private void menuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarActionPerformed
        switch (jTabbedPane2.getSelectedIndex()) {
            case 0:
                EstudanteDao estudanteDao = new EstudanteDao();
                int selectedRowEstudante = this.tabelaEstudante.getSelectedRow();
                String ra = this.tabelaEstudante.getModel().getValueAt(selectedRowEstudante, 0).toString();
                Estudante estudanteSelecionado = this.listaEstudante.stream().filter(estudante -> estudante.getRa().equals(ra)).findFirst().orElse(null);
                
                estudanteSelecionado.setRa(this.tabelaEstudante.getModel().getValueAt(selectedRowEstudante, 0).toString());
                estudanteSelecionado.setNome(this.tabelaEstudante.getModel().getValueAt(selectedRowEstudante, 1).toString());
                estudanteSelecionado.setCpf(this.tabelaEstudante.getModel().getValueAt(selectedRowEstudante, 2).toString());
                estudanteSelecionado.setEmail(this.tabelaEstudante.getModel().getValueAt(selectedRowEstudante, 3).toString());
                estudanteSelecionado.setDataAtualizacao(new Date());

                try {
                    estudanteDao.update(estudanteSelecionado);
                    JOptionPane.showMessageDialog(rootPane, "Estudante editado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Erro ao tentar editar estudante!", "Erro", JOptionPane.ERROR_MESSAGE);
                }

                break;
                
            case 1:
                ArmarioDao armarioDao = new ArmarioDao();
                int selectedRowArmario = this.tabelaArmarios.getSelectedRow();
                Integer numero = Integer.valueOf(this.tabelaArmarios.getModel().getValueAt(selectedRowArmario, 0).toString());
                Armario armarioSelecionado = this.listaArmario.stream().filter(estudante -> estudante.getNumero().equals(numero)).findFirst().orElse(null);
                
                armarioSelecionado.setNumero(Integer.valueOf(this.tabelaArmarios.getModel().getValueAt(selectedRowArmario, 0).toString()));
                armarioSelecionado.setAtivo(Boolean.valueOf(this.tabelaArmarios.getModel().getValueAt(selectedRowArmario, 1).toString()));
                armarioSelecionado.setObservacoes(this.tabelaArmarios.getModel().getValueAt(selectedRowArmario, 2).toString());

                try {
                    armarioDao.update(armarioSelecionado);
                    JOptionPane.showMessageDialog(rootPane, "Armário editado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Erro ao tentar editar armário!", "Erro", JOptionPane.ERROR_MESSAGE);
                }
                
                break;
        }
    }//GEN-LAST:event_menuEditarActionPerformed

    private void menuApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuApagarActionPerformed
                
        switch (jTabbedPane2.getSelectedIndex()) {
            case 0:
                EstudanteDao estudanteDao = new EstudanteDao();
                int selectedRow = this.tabelaEstudante.getSelectedRow();
                String ra = this.tabelaEstudante.getModel().getValueAt(selectedRow, 0).toString();    
                Estudante estudanteSelecionado = this.listaEstudante.stream().filter(estudante -> estudante.getRa().equals(ra)).findFirst().orElse(null);
                       
                estudanteDao.removeById(estudanteSelecionado.getId());
                
                break;
            case 1:
                ArmarioDao armarioDao = new ArmarioDao();
                break;
        }
    }//GEN-LAST:event_menuApagarActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        switch (jTabbedPane2.getSelectedIndex()) {
            case 0:
                buscaEstudantes();
                
                break;
                
            case 1:
                buscaArmarios();
                
                break;
        }
    }//GEN-LAST:event_jTabbedPane2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorHomeBibliotecarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorHomeBibliotecarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorHomeBibliotecarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorHomeBibliotecarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorHomeBibliotecarioUI().setVisible(true);
            }
        });
    }

    public void setDataTable(List<?> lista) {      
        Class<?> classe = lista.get(0).getClass();
        
        switch (classe.getName()) {
            case "br.edu.ifpr.paranavai.armarios.entity.Estudante":

                DefaultTableModel tabelaEstudanteModel = (DefaultTableModel) tabelaEstudante.getModel();

                while (tabelaEstudanteModel.getRowCount() != 0) {
                    tabelaEstudanteModel.removeRow(0);
                }
                
                for (Estudante estudante : (List<Estudante>) lista) {
                    Object[] dataLine = new Object[4];
                    
                    dataLine[0] = estudante.getRa();
                    dataLine[1] = estudante.getNome();
                    dataLine[2] = estudante.getCpf();
                    dataLine[3] = estudante.getEmail();

                    tabelaEstudanteModel.addRow(dataLine);
                }
                
                break;
                
            case "br.edu.ifpr.paranavai.armarios.entity.Armario":
                
                DefaultTableModel tabelaArmarioModel = (DefaultTableModel) tabelaArmarios.getModel();

                while (tabelaArmarioModel.getRowCount() != 0) {
                    tabelaArmarioModel.removeRow(0);
                }
                
                for (Armario armario : (List<Armario>) lista) {
                    Object[] dataLine = new Object[3];
                    
                    dataLine[0] = armario.getNumero();
                    dataLine[1] = armario.getAtivo();
                    dataLine[2] = armario.getObservacoes();

                    tabelaArmarioModel.addRow(dataLine);
                }
                
                break;
        }
    }

    private void buscaEstudantes() {
        this.listaEstudante = new EstudanteDao().finAll();
        this.setDataTable(listaEstudante);
    }
    
    private void buscaArmarios() {
        this.listaArmario = new ArmarioDao().finAll();
        this.setDataTable(listaArmario);
    }
    
    private void iconeFrame(JFrame tela) {
        try {
            URL resource = tela.getClass().getResource("/icones/icon-window.png");
            BufferedImage image = ImageIO.read(resource);
            tela.setIconImage(image);
        } catch (IOException iOException) {
            iOException.printStackTrace();
        }
    }
    
    
    /**
     * Método responsável por dar refresh nas listas a cada 1 minuto (60000 milisegundos)
     */
    private void refreshLists() {
        Timer timer = new Timer(60000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                buscaEstudantes();
                buscaArmarios();
            }
        });
        
        timer.setRepeats(true);
        timer.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscarArmarios;
    private javax.swing.JButton buttonBuscarEstudante;
    private javax.swing.JPanel fields;
    private javax.swing.JPanel fields1;
    private javax.swing.JTextField inputBuscaEstudante;
    private javax.swing.JTextField inputBuscarArmarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menuApagar;
    private javax.swing.JMenuItem menuEditar;
    private javax.swing.JMenuItem menuNovo;
    private javax.swing.JTable tabelaArmarios;
    private javax.swing.JTable tabelaEstudante;
    private javax.swing.JPanel table;
    // End of variables declaration//GEN-END:variables
}
