/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.paranavai.armarios.view;

import br.edu.ifpr.paranavai.armarios.dao.ArmarioDao;
import br.edu.ifpr.paranavai.armarios.dao.EstudanteDao;
import br.edu.ifpr.paranavai.armarios.entity.Estudante;
import br.edu.ifpr.paranavai.armarios.utils.OnlyNumbers;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class EditorHomeBibliotecarioUI extends javax.swing.JFrame {
    
    private List<Estudante> listaEstudante = new ArrayList<>();

    /**
     * Creates new form EditorHomeBibliotecario
     */
    public EditorHomeBibliotecarioUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.buscaEstudantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelNovoEstudante = new javax.swing.JPanel();
        novoEstudanteRA = new javax.swing.JTextField();
        novoEstudanteNome = new javax.swing.JTextField();
        novoEstudanteCPF = new javax.swing.JTextField();
        novoEstudanteEmail = new javax.swing.JTextField();
        buttonSalvarNovoEstudante = new javax.swing.JButton();
        buttonCancelarNovoEstudante = new javax.swing.JButton();
        labelRegistroNovoEstudante = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        fields = new javax.swing.JPanel();
        inputBuscaEstudante = new javax.swing.JTextField();
        buttonBuscarEstudante = new javax.swing.JButton();
        table = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaEstudante = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        fields1 = new javax.swing.JPanel();
        inputBuscarArmarios = new javax.swing.JTextField();
        buttonBuscarArmarios = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuNovo = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenuItem();
        menuApagar = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        novoEstudanteRA.setText("RA");

        novoEstudanteNome.setText("Nome");

        novoEstudanteCPF.setText("CPF");

        novoEstudanteEmail.setText("E-mail");

        buttonSalvarNovoEstudante.setText("Salvar");
        buttonSalvarNovoEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarNovoEstudanteActionPerformed(evt);
            }
        });

        buttonCancelarNovoEstudante.setText("Cancelar");

        labelRegistroNovoEstudante.setText("REGISTRO NOVO ESTUDANTE");

        javax.swing.GroupLayout panelNovoEstudanteLayout = new javax.swing.GroupLayout(panelNovoEstudante);
        panelNovoEstudante.setLayout(panelNovoEstudanteLayout);
        panelNovoEstudanteLayout.setHorizontalGroup(
            panelNovoEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNovoEstudanteLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(panelNovoEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(novoEstudanteNome)
                    .addComponent(novoEstudanteCPF)
                    .addComponent(novoEstudanteEmail)
                    .addGroup(panelNovoEstudanteLayout.createSequentialGroup()
                        .addComponent(buttonCancelarNovoEstudante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(buttonSalvarNovoEstudante))
                    .addComponent(novoEstudanteRA))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNovoEstudanteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelRegistroNovoEstudante)
                .addGap(97, 97, 97))
        );
        panelNovoEstudanteLayout.setVerticalGroup(
            panelNovoEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNovoEstudanteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelRegistroNovoEstudante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(novoEstudanteRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(novoEstudanteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(novoEstudanteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(novoEstudanteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(panelNovoEstudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSalvarNovoEstudante)
                    .addComponent(buttonCancelarNovoEstudante))
                .addGap(18, 18, 18))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        inputBuscaEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBuscaEstudanteActionPerformed(evt);
            }
        });

        buttonBuscarEstudante.setText("Buscar");
        buttonBuscarEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarEstudanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fieldsLayout = new javax.swing.GroupLayout(fields);
        fields.setLayout(fieldsLayout);
        fieldsLayout.setHorizontalGroup(
            fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(inputBuscaEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBuscarEstudante)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        fieldsLayout.setVerticalGroup(
            fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBuscaEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarEstudante))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.add(fields, java.awt.BorderLayout.PAGE_START);

        table.setLayout(new java.awt.BorderLayout());

        tabelaEstudante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RA", "Nome", "CPF", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tabelaEstudante);

        table.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanel2.add(table, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Estudantes", jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        inputBuscarArmarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBuscarArmariosActionPerformed(evt);
            }
        });

        buttonBuscarArmarios.setText("Buscar");
        buttonBuscarArmarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarArmariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fields1Layout = new javax.swing.GroupLayout(fields1);
        fields1.setLayout(fields1Layout);
        fields1Layout.setHorizontalGroup(
            fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fields1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(inputBuscarArmarios, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBuscarArmarios)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        fields1Layout.setVerticalGroup(
            fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fields1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBuscarArmarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscarArmarios))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.add(fields1, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Armários", jPanel1);

        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        menu.setText("Menu");

        menuNovo.setText("Novo");
        menuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoActionPerformed(evt);
            }
        });
        menu.add(menuNovo);

        menuEditar.setText("Editar");
        menuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarActionPerformed(evt);
            }
        });
        menu.add(menuEditar);

        menuApagar.setText("Apagar");
        menuApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuApagarActionPerformed(evt);
            }
        });
        menu.add(menuApagar);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputBuscaEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBuscaEstudanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBuscaEstudanteActionPerformed

    private void buttonBuscarEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarEstudanteActionPerformed
        List<Estudante> listaEstudanteFiltrada = this.listaEstudante.stream()
                .filter(l -> l.getNome().toUpperCase()
                .contains(this.inputBuscaEstudante.getText().toUpperCase())
                || l.getCpf()
                        .contains(this.inputBuscaEstudante.getText())
                || l.getRa()
                        .contains(this.inputBuscaEstudante.getText())
                || l.getEmail().toUpperCase()
                        .contains(this.inputBuscaEstudante.getText().toUpperCase()))
                .collect(Collectors.toList());

        this.setDataTable(listaEstudanteFiltrada);
    }//GEN-LAST:event_buttonBuscarEstudanteActionPerformed

    private void inputBuscarArmariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBuscarArmariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBuscarArmariosActionPerformed

    private void buttonBuscarArmariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarArmariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscarArmariosActionPerformed

    private void menuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNovoActionPerformed
        switch (jTabbedPane2.getSelectedIndex()) {
            case 0:
                NovoEstudanteUI novoEstudanteUI = new NovoEstudanteUI();

                this.iconeFrame(novoEstudanteUI);
                novoEstudanteUI.setTitle("Cadastro Novo Estudante");
                novoEstudanteUI.setVisible(true);

                break;
                
            case 1:
                
                break;
        }
    }//GEN-LAST:event_menuNovoActionPerformed

    private void menuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarActionPerformed
        switch (jTabbedPane2.getSelectedIndex()) {
            case 0:
                EstudanteDao estudanteDao = new EstudanteDao();
                int selectedRow = this.tabelaEstudante.getSelectedRow();
                String ra = this.tabelaEstudante.getModel().getValueAt(selectedRow, 0).toString();
                Estudante estudanteSelecionado = this.listaEstudante.stream().filter(estudante -> estudante.getRa().equals(ra)).findFirst().orElse(null);
                
                estudanteSelecionado.setRa(this.tabelaEstudante.getModel().getValueAt(selectedRow, 0).toString());
                estudanteSelecionado.setNome(this.tabelaEstudante.getModel().getValueAt(selectedRow, 1).toString());
                estudanteSelecionado.setCpf(this.tabelaEstudante.getModel().getValueAt(selectedRow, 2).toString());
                estudanteSelecionado.setEmail(this.tabelaEstudante.getModel().getValueAt(selectedRow, 3).toString());
                estudanteSelecionado.setDataAtualizacao(new Date());

                try {
                    estudanteDao.update(estudanteSelecionado);
                    JOptionPane.showMessageDialog(rootPane, "Estudante editado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Erro ao tentar editar estudante!", "Erro", JOptionPane.ERROR_MESSAGE);
                }

                break;
                
            case 1:
                ArmarioDao armarioDao = new ArmarioDao();
                break;
        }
    }//GEN-LAST:event_menuEditarActionPerformed

    private void menuApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuApagarActionPerformed
                
        switch (jTabbedPane2.getSelectedIndex()) {
            case 0:
                EstudanteDao estudanteDao = new EstudanteDao();
                int selectedRow = this.tabelaEstudante.getSelectedRow();
                String ra = this.tabelaEstudante.getModel().getValueAt(selectedRow, 0).toString();    
                Estudante estudanteSelecionado = this.listaEstudante.stream().filter(estudante -> estudante.getRa().equals(ra)).findFirst().orElse(null);
                       
                estudanteDao.removeById(estudanteSelecionado.getId());
                
                break;
            case 1:
                ArmarioDao armarioDao = new ArmarioDao();
                break;
        }
    }//GEN-LAST:event_menuApagarActionPerformed

    private void buttonSalvarNovoEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarNovoEstudanteActionPerformed
        Estudante novoEstudante = new Estudante();
        novoEstudante.setRa(this.novoEstudanteRA.getText());
        novoEstudante.setNome(this.novoEstudanteNome.getText());
        novoEstudante.setCpf(this.novoEstudanteCPF.getText());
        novoEstudante.setEmail(this.novoEstudanteEmail.getText());

        try {
            new EstudanteDao().save(novoEstudante);
            JOptionPane.showMessageDialog(rootPane, "Estudante criado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Erro ao criar estudante!", "Erro", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonSalvarNovoEstudanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorHomeBibliotecarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorHomeBibliotecarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorHomeBibliotecarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorHomeBibliotecarioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorHomeBibliotecarioUI().setVisible(true);
            }
        });
    }

    public void setDataTable(List<Estudante> listaEstudantes) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tabelaEstudante.getModel();

        while (defaultTableModel.getRowCount() != 0) {
            defaultTableModel.removeRow(0);
        }

        for (Estudante estudante : listaEstudantes) {
            Object[] dataLine = new Object[4];
            dataLine[0] = estudante.getRa();
            dataLine[1] = estudante.getNome();
            dataLine[2] = estudante.getCpf();
            dataLine[3] = estudante.getEmail();

            defaultTableModel.addRow(dataLine);
        }
    }

    public void buscaEstudantes() {
        this.listaEstudante = new EstudanteDao().finAll();
        this.setDataTable(listaEstudante);
    }
    
    private void iconeFrame(JFrame tela) {
        try {
            URL resource = tela.getClass().getResource("/icones/icon-window.png");
            BufferedImage image = ImageIO.read(resource);
            tela.setIconImage(image);
        } catch (IOException iOException) {
            iOException.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscarArmarios;
    private javax.swing.JButton buttonBuscarEstudante;
    private javax.swing.JButton buttonCancelarNovoEstudante;
    private javax.swing.JButton buttonSalvarNovoEstudante;
    private javax.swing.JPanel fields;
    private javax.swing.JPanel fields1;
    private javax.swing.JTextField inputBuscaEstudante;
    private javax.swing.JTextField inputBuscarArmarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelRegistroNovoEstudante;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem menuApagar;
    private javax.swing.JMenuItem menuEditar;
    private javax.swing.JMenuItem menuNovo;
    private javax.swing.JTextField novoEstudanteCPF;
    private javax.swing.JTextField novoEstudanteEmail;
    private javax.swing.JTextField novoEstudanteNome;
    private javax.swing.JTextField novoEstudanteRA;
    private javax.swing.JPanel panelNovoEstudante;
    private javax.swing.JTable tabelaEstudante;
    private javax.swing.JPanel table;
    // End of variables declaration//GEN-END:variables
}
