/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.paranavai.armarios.view;

import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class EditorHomeBibliotecario extends javax.swing.JFrame {

    /**
     * Creates new form EditorHomeBibliotecario
     */
    public EditorHomeBibliotecario() {
        initComponents();
        this.buscaEstudantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        fields = new javax.swing.JPanel();
        inputField = new javax.swing.JTextField();
        buttonBuscar = new javax.swing.JButton();
        table = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.BorderLayout());

        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });

        buttonBuscar.setText("Buscar");

        javax.swing.GroupLayout fieldsLayout = new javax.swing.GroupLayout(fields);
        fields.setLayout(fieldsLayout);
        fieldsLayout.setHorizontalGroup(
            fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fieldsLayout.setVerticalGroup(
            fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fieldsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBuscar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.add(fields, java.awt.BorderLayout.PAGE_START);

        table.setLayout(new java.awt.BorderLayout());

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RA", "Nome", "CPF", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable7);

        table.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanel2.add(table, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Estudantes", jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jTabbedPane2.addTab("Armários", jPanel1);

        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorHomeBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorHomeBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorHomeBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorHomeBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorHomeBibliotecario().setVisible(true);
            }
        });
    }

    public void setDataTable(List<Estudante> listaEstudantes) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tabelaEstudante.getModel();

        while (defaultTableModel.getRowCount() != 0) {
            defaultTableModel.removeRow(0);
        }

        for (Estudante estudante : listaEstudantes) {
            Object[] dataLine = new Object[4];
            dataLine[0] = estudante.getNome();
            dataLine[1] = estudante.getCpf();
            dataLine[2] = estudante.getRa();
            dataLine[3] = estudante.getEmail();

            defaultTableModel.addRow(dataLine);
        }
    }

    public void buscaEstudantes() {
        this.listaEstudante = new EstudanteDao().finAll();
        this.setDataTable(listaEstudante);
    }

    private void buttonBuscaActionPerformed(java.awt.event.ActionEvent evt) {
        List<Estudante> listaEstudanteFiltrada = this.listaEstudante.stream()
                .filter(l -> l.getNome()
                .contains(this.inputBusca.getText())
                || l.getCpf()
                        .contains(this.inputBusca.getText())
                || l.getRa()
                        .contains(this.inputBusca.getText())
                || l.getEmail()
                        .contains(this.inputBusca.getText()))
                .collect(Collectors.toList());

        this.setDataTable(listaEstudanteFiltrada);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JPanel fields;
    private javax.swing.JTextField inputField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable7;
    private javax.swing.JPanel table;
    // End of variables declaration//GEN-END:variables
}
